### ISSUE TITLE
Error when using Search Extensions with Unity 2021.3

### ISSUE THREAD

**Issue by ryu3taki** [Unity-Technologies/com.unity.search.extensions#56]
I'm using Search Extensions with Unity 2021.3, and I encountered some errors when I updated the package. Here are the error messages I received:
```
Library\PackageCache\com.unity.search.extensions@5cf58b16f8\Indexing\TextureCustomIndexing.cs(22,17): error CS0308: The non-generic method 'ObjectIndexer.IndexProperty(int, string, string, bool, bool)' cannot be used with type arguments
```
```
Library\PackageCache\com.unity.search.extensions@5cf58b16f8\Indexing\ShaderIndexing.cs(48,25): error CS0308: The non-generic method 'ObjectIndexer.IndexProperty(int, string, string, bool, bool)' cannot be used with type arguments
```

It appears that the generic version of  `ObjectIndexer.IndexProperty` (added in [this commit](https://github.com/Unity-Technologies/com.unity.search.extensions/commit/9957b44b1972ed6759d5ff6899df0086529b6128)) is available for newer versions of Unity but not for 2021.3, despite the README stating that "The Search Extensions package will work with Unity 2020.3 and **any other versions higher than 2021.2.**"
Could you please address this issue so that it works with Unity 2021.3, or update the support versions description in the README? Thank you!
